//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minesmart.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResHindi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResHindi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("minesmart.Resource.ResHindi", typeof(ResHindi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टेस्ट ऐन्ड सर्च.
        /// </summary>
        internal static string btncameradtl_Text {
            get {
                return ResourceManager.GetString("btncameradtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टेस्ट ऐन्ड सर्च.
        /// </summary>
        internal static string btncameradtlText {
            get {
                return ResourceManager.GetString("btncameradtlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जा.
        /// </summary>
        internal static string btncgo_Text {
            get {
                return ResourceManager.GetString("btncgo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टेस्ट ऐन्ड सर्च.
        /// </summary>
        internal static string btnCompanydtl_Text {
            get {
                return ResourceManager.GetString("btnCompanydtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लॉग इन करें.
        /// </summary>
        internal static string btnLogin_Text {
            get {
                return ResourceManager.GetString("btnLogin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जेनरेट.
        /// </summary>
        internal static string btnSave_Text {
            get {
                return ResourceManager.GetString("btnSave.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जेनरेट.
        /// </summary>
        internal static string btnSaveWeightSlip_Text {
            get {
                return ResourceManager.GetString("btnSaveWeightSlip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to खोज.
        /// </summary>
        internal static string btnsearch_Text {
            get {
                return ResourceManager.GetString("btnsearch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टेस्ट ऐन्ड सर्च.
        /// </summary>
        internal static string btnserialport_Text {
            get {
                return ResourceManager.GetString("btnserialport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काउन्ट.
        /// </summary>
        internal static string btntpassline_Text {
            get {
                return ResourceManager.GetString("btntpassline.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जेनरेट.
        /// </summary>
        internal static string btnunconfirmrawanna_Text {
            get {
                return ResourceManager.GetString("btnunconfirmrawanna.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काउन्ट.
        /// </summary>
        internal static string button1_Text {
            get {
                return ResourceManager.GetString("button1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जेनरेट.
        /// </summary>
        internal static string button2_Text {
            get {
                return ResourceManager.GetString("button2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काउन्ट.
        /// </summary>
        internal static string button3_Text {
            get {
                return ResourceManager.GetString("button3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टन.
        /// </summary>
        internal static string button4_Text {
            get {
                return ResourceManager.GetString("button4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काउन्ट.
        /// </summary>
        internal static string button5_Text {
            get {
                return ResourceManager.GetString("button5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टन.
        /// </summary>
        internal static string button6_Text {
            get {
                return ResourceManager.GetString("button6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टन.
        /// </summary>
        internal static string button7_Text {
            get {
                return ResourceManager.GetString("button7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अमाउन्ट.
        /// </summary>
        internal static string button8_Text {
            get {
                return ResourceManager.GetString("button8.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परिवहन साधन.
        /// </summary>
        internal static string cccccccc {
            get {
                return ResourceManager.GetString("cccccccc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to विभाग प्रिन्ट.
        /// </summary>
        internal static string Chkconfirmdmg_Text {
            get {
                return ResourceManager.GetString("Chkconfirmdmg.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रिन्ट.
        /// </summary>
        internal static string chkconfirmprint_Text {
            get {
                return ResourceManager.GetString("chkconfirmprint.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to विभाग प्रिन्ट.
        /// </summary>
        internal static string chkdmgtpass_Text {
            get {
                return ResourceManager.GetString("chkdmgtpass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to विभाग प्रिन्ट.
        /// </summary>
        internal static string chkdmgunconfirmprint_Text {
            get {
                return ResourceManager.GetString("chkdmgunconfirmprint.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to विभाग प्रिन्ट.
        /// </summary>
        internal static string chkdmguntpass_Text {
            get {
                return ResourceManager.GetString("chkdmguntpass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सेव डिटैल्ज़.
        /// </summary>
        internal static string chkissaved_Text {
            get {
                return ResourceManager.GetString("chkissaved.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रिन्ट डिटैल्ज़.
        /// </summary>
        internal static string chkprintdtl_Text {
            get {
                return ResourceManager.GetString("chkprintdtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रिन्ट.
        /// </summary>
        internal static string chkprinttpass_Text {
            get {
                return ResourceManager.GetString("chkprinttpass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रिन्ट.
        /// </summary>
        internal static string chkprintuntpass_Text {
            get {
                return ResourceManager.GetString("chkprintuntpass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रिंट.
        /// </summary>
        internal static string chkunconfirmprint_Text {
            get {
                return ResourceManager.GetString("chkunconfirmprint.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जेनरेट.
        /// </summary>
        internal static string CTbtnSave_Text {
            get {
                return ResourceManager.GetString("CTbtnSave.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जा.
        /// </summary>
        internal static string CTbutton1_Text {
            get {
                return ResourceManager.GetString("CTbutton1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लॉगिन आईडी.
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पासवर्ड.
        /// </summary>
        internal static string label3_Text {
            get {
                return ResourceManager.GetString("label3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to भाषा.
        /// </summary>
        internal static string label5_Text {
            get {
                return ResourceManager.GetString("label5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पता.
        /// </summary>
        internal static string lblAddress_Text {
            get {
                return ResourceManager.GetString("lblAddress.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लगभग दूरी.
        /// </summary>
        internal static string lblapproxdistnce_Text {
            get {
                return ResourceManager.GetString("lblapproxdistnce.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लगभग समय.
        /// </summary>
        internal static string lblapproxtime_Text {
            get {
                return ResourceManager.GetString("lblapproxtime.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बैक कैमरा यूआरएल.
        /// </summary>
        internal static string lblbackameraurl_Text {
            get {
                return ResourceManager.GetString("lblbackameraurl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कैमरा आईपी पता दूसरा.
        /// </summary>
        internal static string lblbackcameraIpaddress_Text {
            get {
                return ResourceManager.GetString("lblbackcameraIpaddress.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पासवर्ड.
        /// </summary>
        internal static string lblbackpassword_Text {
            get {
                return ResourceManager.GetString("lblbackpassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to यूज़र नेम.
        /// </summary>
        internal static string lblbackusername_Text {
            get {
                return ResourceManager.GetString("lblbackusername.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बॉड दर.
        /// </summary>
        internal static string lblbaudrate_Text {
            get {
                return ResourceManager.GetString("lblbaudrate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ब्रिज नंबर.
        /// </summary>
        internal static string lblbridgeno_Text {
            get {
                return ResourceManager.GetString("lblbridgeno.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कैमरा आईपी पता सामने.
        /// </summary>
        internal static string lblcameraipaddress_Text {
            get {
                return ResourceManager.GetString("lblcameraipaddress.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to संस्थान के विवरण.
        /// </summary>
        internal static string lblcompanydtlws_Text {
            get {
                return ResourceManager.GetString("lblcompanydtlws.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कंपनी का नाम.
        /// </summary>
        internal static string lblcompanyname_Text {
            get {
                return ResourceManager.GetString("lblcompanyname.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पार्टी डिटैल्ज़.
        /// </summary>
        internal static string lblcondigndtl_Text {
            get {
                return ResourceManager.GetString("lblcondigndtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सामने का कैमरा.
        /// </summary>
        internal static string lblConfcamera1_Text {
            get {
                return ResourceManager.GetString("lblConfcamera1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिछला कैमरा.
        /// </summary>
        internal static string lblConRcamera_Text {
            get {
                return ResourceManager.GetString("lblConRcamera.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जीएसटी.
        /// </summary>
        internal static string lblconsigneegst_Text {
            get {
                return ResourceManager.GetString("lblconsigneegst.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नाम.
        /// </summary>
        internal static string lblconsigneename_Text {
            get {
                return ResourceManager.GetString("lblconsigneename.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शेष राशि.
        /// </summary>
        internal static string lblcRemainBalance_Text {
            get {
                return ResourceManager.GetString("lblcRemainBalance.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लगभग समय.
        /// </summary>
        internal static string lblctapproxtime_Text {
            get {
                return ResourceManager.GetString("lblctapproxtime.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to क्षमता.
        /// </summary>
        internal static string lblctcapacity_Text {
            get {
                return ResourceManager.GetString("lblctcapacity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पार्टी डिटैल्ज़.
        /// </summary>
        internal static string lblctconsdt_Text {
            get {
                return ResourceManager.GetString("lblctconsdt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पता.
        /// </summary>
        internal static string lblctconsigneeaddrs_Text {
            get {
                return ResourceManager.GetString("lblctconsigneeaddrs.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नाम.
        /// </summary>
        internal static string lblctconsigneename_Text {
            get {
                return ResourceManager.GetString("lblctconsigneename.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to विक्रेता का नाम.
        /// </summary>
        internal static string lblctdealername_Text {
            get {
                return ResourceManager.GetString("lblctdealername.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चालक मोबाइल नंबर.
        /// </summary>
        internal static string lblctdrivermobileno_Text {
            get {
                return ResourceManager.GetString("lblctdrivermobileno.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चालक का नाम.
        /// </summary>
        internal static string lblctdrivername_Text {
            get {
                return ResourceManager.GetString("lblctdrivername.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिछला कैमरा.
        /// </summary>
        internal static string lblctfcamera_Text {
            get {
                return ResourceManager.GetString("lblctfcamera.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कुल वजन.
        /// </summary>
        internal static string lblctgrossweight_Text {
            get {
                return ResourceManager.GetString("lblctgrossweight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जीएसटी.
        /// </summary>
        internal static string lblctgstno_Text {
            get {
                return ResourceManager.GetString("lblctgstno.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थान.
        /// </summary>
        internal static string lblctlocation_Text {
            get {
                return ResourceManager.GetString("lblctlocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मिनरल्स.
        /// </summary>
        internal static string lblctmineral_Text {
            get {
                return ResourceManager.GetString("lblctmineral.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मिनरल स्टॉक बैलेंस.
        /// </summary>
        internal static string lblctmineralstocket_Text {
            get {
                return ResourceManager.GetString("lblctmineralstocket.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मिनरल्स यूज़्ड फॉर.
        /// </summary>
        internal static string lblctmineraluserfor_Text {
            get {
                return ResourceManager.GetString("lblctmineraluserfor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to खनिज का वजन.
        /// </summary>
        internal static string lblctnetweight_Text {
            get {
                return ResourceManager.GetString("lblctnetweight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ट्रांज़िट पास की पुष्टि करें.
        /// </summary>
        internal static string lblctpas_Text {
            get {
                return ResourceManager.GetString("lblctpas.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सामने का कैमरा.
        /// </summary>
        internal static string lblctrcamera_Text {
            get {
                return ResourceManager.GetString("lblctrcamera.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टिप्पणी.
        /// </summary>
        internal static string lblctremarks_Text {
            get {
                return ResourceManager.GetString("lblctremarks.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ख़ाली गाड़ी का वजन.
        /// </summary>
        internal static string lblcttareweight_Text {
            get {
                return ResourceManager.GetString("lblcttareweight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परिवहन साधन.
        /// </summary>
        internal static string lblcttransportmode_Text {
            get {
                return ResourceManager.GetString("lblcttransportmode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परिवहन विवरण.
        /// </summary>
        internal static string lblcttrasportdtl_Text {
            get {
                return ResourceManager.GetString("lblcttrasportdtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गाडी नंबर.
        /// </summary>
        internal static string lblctvehicelno_Text {
            get {
                return ResourceManager.GetString("lblctvehicelno.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वाहन का वजन.
        /// </summary>
        internal static string lblctvehicleweight_Text {
            get {
                return ResourceManager.GetString("lblctvehicleweight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वजन विवरण.
        /// </summary>
        internal static string lblctweightdtl_Text {
            get {
                return ResourceManager.GetString("lblctweightdtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वजन विवरण.
        /// </summary>
        internal static string lblcweightdtl_Text {
            get {
                return ResourceManager.GetString("lblcweightdtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डेटा बिट्स.
        /// </summary>
        internal static string lbldatabits_Text {
            get {
                return ResourceManager.GetString("lbldatabits.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to विक्रेता का नाम.
        /// </summary>
        internal static string lbldealarname_Text {
            get {
                return ResourceManager.GetString("lbldealarname.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रवाना.
        /// </summary>
        internal static string lbldrawanna_Text {
            get {
                return ResourceManager.GetString("lbldrawanna.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चालक का नाम.
        /// </summary>
        internal static string lbldrivename_Text {
            get {
                return ResourceManager.GetString("lbldrivename.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चालक मोबाइल नंबर.
        /// </summary>
        internal static string lbldrivermobile_Text {
            get {
                return ResourceManager.GetString("lbldrivermobile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थापना.
        /// </summary>
        internal static string lbldsetting_Text {
            get {
                return ResourceManager.GetString("lbldsetting.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ट्रांजिट पास.
        /// </summary>
        internal static string lbldtranistpass_Text {
            get {
                return ResourceManager.GetString("lbldtranistpass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काटा पार्च.
        /// </summary>
        internal static string lbldweightslip_Text {
            get {
                return ResourceManager.GetString("lbldweightslip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ईमेल आईडी.
        /// </summary>
        internal static string lblEmailId_Text {
            get {
                return ResourceManager.GetString("lblEmailId.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to फ्रंट कैमरा यूआरएल.
        /// </summary>
        internal static string lblfrntcameradtl_Text {
            get {
                return ResourceManager.GetString("lblfrntcameradtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कुल वजन.
        /// </summary>
        internal static string lblgrossweight_Text {
            get {
                return ResourceManager.GetString("lblgrossweight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सहायता.
        /// </summary>
        internal static string lblhreport_Text {
            get {
                return ResourceManager.GetString("lblhreport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to इन्वॉइस.
        /// </summary>
        internal static string lblinvoice_Text {
            get {
                return ResourceManager.GetString("lblinvoice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to उल्टा है.
        /// </summary>
        internal static string lblisreversed_Text {
            get {
                return ResourceManager.GetString("lblisreversed.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नाम.
        /// </summary>
        internal static string lblloginusername_Text {
            get {
                return ResourceManager.GetString("lblloginusername.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कन्फर्म रवाना.
        /// </summary>
        internal static string lblmainconfirmrawann_Text {
            get {
                return ResourceManager.GetString("lblmainconfirmrawann.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डैशबोर्ड.
        /// </summary>
        internal static string lblmenusdashboard_Text {
            get {
                return ResourceManager.GetString("lblmenusdashboard.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मिनरल्स.
        /// </summary>
        internal static string lblmineral_Text {
            get {
                return ResourceManager.GetString("lblmineral.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मिनरल्स यूज़्ड फॉर.
        /// </summary>
        internal static string lblmineraluserfor_Text {
            get {
                return ResourceManager.GetString("lblmineraluserfor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एमएल नंबर.
        /// </summary>
        internal static string lblmlno_Text {
            get {
                return ResourceManager.GetString("lblmlno.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डैशबोर्ड.
        /// </summary>
        internal static string lblMnudashboard_Text {
            get {
                return ResourceManager.GetString("lblMnudashboard.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डैशबोर्ड.
        /// </summary>
        internal static string lblmnuddashboard_Text {
            get {
                return ResourceManager.GetString("lblmnuddashboard.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सहायता.
        /// </summary>
        internal static string lblmnudhelp_Text {
            get {
                return ResourceManager.GetString("lblmnudhelp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चलाना.
        /// </summary>
        internal static string lblmnudinvoice_Text {
            get {
                return ResourceManager.GetString("lblmnudinvoice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लॉग आउट.
        /// </summary>
        internal static string lblmnudlogout_Text {
            get {
                return ResourceManager.GetString("lblmnudlogout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रिपोर्ट.
        /// </summary>
        internal static string lblmnudreport_Text {
            get {
                return ResourceManager.GetString("lblmnudreport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सहायता.
        /// </summary>
        internal static string lblmnuhelp_Text {
            get {
                return ResourceManager.GetString("lblmnuhelp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डैशबोर्ड.
        /// </summary>
        internal static string lblmnuhpdashboard_Text {
            get {
                return ResourceManager.GetString("lblmnuhpdashboard.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सहायता.
        /// </summary>
        internal static string lblmnuhphelp_Text {
            get {
                return ResourceManager.GetString("lblmnuhphelp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चलाना.
        /// </summary>
        internal static string lblmnuhpinvoice_Text {
            get {
                return ResourceManager.GetString("lblmnuhpinvoice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लॉग आउट.
        /// </summary>
        internal static string lblmnuhplogout_Text {
            get {
                return ResourceManager.GetString("lblmnuhplogout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रवाना.
        /// </summary>
        internal static string lblmnuhprawanna_Text {
            get {
                return ResourceManager.GetString("lblmnuhprawanna.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थापना.
        /// </summary>
        internal static string lblmnuhpsetting_Text {
            get {
                return ResourceManager.GetString("lblmnuhpsetting.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ट्रांजिट पास.
        /// </summary>
        internal static string lblmnuhptpass_Text {
            get {
                return ResourceManager.GetString("lblmnuhptpass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काटा पार्च.
        /// </summary>
        internal static string lblmnuhpwslip_Text {
            get {
                return ResourceManager.GetString("lblmnuhpwslip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डैशबोर्ड.
        /// </summary>
        internal static string lblmnuindashboard_Text {
            get {
                return ResourceManager.GetString("lblmnuindashboard.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चलाना.
        /// </summary>
        internal static string lblmnuininvoice_Text {
            get {
                return ResourceManager.GetString("lblmnuininvoice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रिपोर्ट.
        /// </summary>
        internal static string lblmnuinreport_Text {
            get {
                return ResourceManager.GetString("lblmnuinreport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रवाना.
        /// </summary>
        internal static string lblmnuinrwanna_Text {
            get {
                return ResourceManager.GetString("lblmnuinrwanna.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थापना.
        /// </summary>
        internal static string lblmnuinsetting_Text {
            get {
                return ResourceManager.GetString("lblmnuinsetting.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ट्रांजिट पास.
        /// </summary>
        internal static string lblmnuintpass_Text {
            get {
                return ResourceManager.GetString("lblmnuintpass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सहायता.
        /// </summary>
        internal static string lblmnuinvhelp_Text {
            get {
                return ResourceManager.GetString("lblmnuinvhelp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लॉग आउट.
        /// </summary>
        internal static string lblmnuinvlogout_Text {
            get {
                return ResourceManager.GetString("lblmnuinvlogout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चलाना.
        /// </summary>
        internal static string lblmnuinvoice_Text {
            get {
                return ResourceManager.GetString("lblmnuinvoice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काटा पार्च.
        /// </summary>
        internal static string lblmnuinwslip_Text {
            get {
                return ResourceManager.GetString("lblmnuinwslip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डैशबोर्ड.
        /// </summary>
        internal static string lblmnulgdashbrd_Text {
            get {
                return ResourceManager.GetString("lblmnulgdashbrd.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सहायता.
        /// </summary>
        internal static string lblmnulghelp_Text {
            get {
                return ResourceManager.GetString("lblmnulghelp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चलाना.
        /// </summary>
        internal static string lblmnulginvoice_Text {
            get {
                return ResourceManager.GetString("lblmnulginvoice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लॉग आउट.
        /// </summary>
        internal static string lblmnulglogout_Text {
            get {
                return ResourceManager.GetString("lblmnulglogout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रवाना.
        /// </summary>
        internal static string lblmnulgrawanna_Text {
            get {
                return ResourceManager.GetString("lblmnulgrawanna.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT.
        /// </summary>
        internal static string lblmnulgreport_Text {
            get {
                return ResourceManager.GetString("lblmnulgreport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थापना.
        /// </summary>
        internal static string lblmnulgsetting_Text {
            get {
                return ResourceManager.GetString("lblmnulgsetting.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ट्रांजिट पास.
        /// </summary>
        internal static string lblmnulgtpass_Text {
            get {
                return ResourceManager.GetString("lblmnulgtpass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काटा पार्च.
        /// </summary>
        internal static string lblmnulgweightslip_Text {
            get {
                return ResourceManager.GetString("lblmnulgweightslip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रवाना.
        /// </summary>
        internal static string lblMnuRawanna_Text {
            get {
                return ResourceManager.GetString("lblMnuRawanna.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लॉग आउट.
        /// </summary>
        internal static string lblMnurlogout_Text {
            get {
                return ResourceManager.GetString("lblMnurlogout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रिपोर्ट.
        /// </summary>
        internal static string lblmnurpreport_Text {
            get {
                return ResourceManager.GetString("lblmnurpreport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डैशबोर्ड.
        /// </summary>
        internal static string lblmnurptdashboard_Text {
            get {
                return ResourceManager.GetString("lblmnurptdashboard.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चलाना.
        /// </summary>
        internal static string lblmnurptinvoice_Text {
            get {
                return ResourceManager.GetString("lblmnurptinvoice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लॉग आउट.
        /// </summary>
        internal static string lblmnurptogout_Text {
            get {
                return ResourceManager.GetString("lblmnurptogout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रवाना.
        /// </summary>
        internal static string lblmnurptrawanna_Text {
            get {
                return ResourceManager.GetString("lblmnurptrawanna.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थापना.
        /// </summary>
        internal static string lblmnurptsetting_Text {
            get {
                return ResourceManager.GetString("lblmnurptsetting.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ट्रांजिट पास.
        /// </summary>
        internal static string lblmnurpttpass_Text {
            get {
                return ResourceManager.GetString("lblmnurpttpass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काटा पार्च.
        /// </summary>
        internal static string lblmnurpwslip_Text {
            get {
                return ResourceManager.GetString("lblmnurpwslip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सहायता.
        /// </summary>
        internal static string lblMnurwhelp_Text {
            get {
                return ResourceManager.GetString("lblMnurwhelp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चलाना.
        /// </summary>
        internal static string lblMnurwinvoice_Text {
            get {
                return ResourceManager.GetString("lblMnurwinvoice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रिपोर्ट.
        /// </summary>
        internal static string lblMnurwreport_Text {
            get {
                return ResourceManager.GetString("lblMnurwreport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थापना.
        /// </summary>
        internal static string lblMnusetting_Text {
            get {
                return ResourceManager.GetString("lblMnusetting.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लॉग आउट.
        /// </summary>
        internal static string lblmnuslogout_Text {
            get {
                return ResourceManager.GetString("lblmnuslogout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रवाना.
        /// </summary>
        internal static string lblmnusrawanna_Text {
            get {
                return ResourceManager.GetString("lblmnusrawanna.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ट्रांजिट पास.
        /// </summary>
        internal static string lblmnustpass_Text {
            get {
                return ResourceManager.GetString("lblmnustpass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डैशबोर्ड.
        /// </summary>
        internal static string lblmnutdashboard_Text {
            get {
                return ResourceManager.GetString("lblmnutdashboard.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सहायता.
        /// </summary>
        internal static string lblmnuthelp_Text {
            get {
                return ResourceManager.GetString("lblmnuthelp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चलाना.
        /// </summary>
        internal static string lblmnutinvoice_Text {
            get {
                return ResourceManager.GetString("lblmnutinvoice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लॉग आउट.
        /// </summary>
        internal static string lblmnutlogout_Text {
            get {
                return ResourceManager.GetString("lblmnutlogout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ट्रांजिट पास.
        /// </summary>
        internal static string lblMnuTPass_Text {
            get {
                return ResourceManager.GetString("lblMnuTPass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रवाना.
        /// </summary>
        internal static string lblmnutrawanna_Text {
            get {
                return ResourceManager.GetString("lblmnutrawanna.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रिपोर्ट.
        /// </summary>
        internal static string lblmnutreport_Text {
            get {
                return ResourceManager.GetString("lblmnutreport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थापना.
        /// </summary>
        internal static string lblmnutsetting_Text {
            get {
                return ResourceManager.GetString("lblmnutsetting.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ट्रांजिट पास.
        /// </summary>
        internal static string lblmnuttpass_Text {
            get {
                return ResourceManager.GetString("lblmnuttpass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काटा पार्च.
        /// </summary>
        internal static string lblmnutweightslip_Text {
            get {
                return ResourceManager.GetString("lblmnutweightslip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to डैशबोर्ड.
        /// </summary>
        internal static string lblmnuwdashboard_Text {
            get {
                return ResourceManager.GetString("lblmnuwdashboard.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काटा पार्च.
        /// </summary>
        internal static string lblMnuWghtslp_Text {
            get {
                return ResourceManager.GetString("lblMnuWghtslp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सहायता.
        /// </summary>
        internal static string lblmnuwhelp_Text {
            get {
                return ResourceManager.GetString("lblmnuwhelp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चलाना.
        /// </summary>
        internal static string lblmnuwinvoice_Text {
            get {
                return ResourceManager.GetString("lblmnuwinvoice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लॉग आउट.
        /// </summary>
        internal static string lblmnuwlogout_Text {
            get {
                return ResourceManager.GetString("lblmnuwlogout.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रिपोर्ट.
        /// </summary>
        internal static string lblmnuwreport_Text {
            get {
                return ResourceManager.GetString("lblmnuwreport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थापना.
        /// </summary>
        internal static string lblmnuwsetting_Text {
            get {
                return ResourceManager.GetString("lblmnuwsetting.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ट्रांजिट पास.
        /// </summary>
        internal static string lblmnuwtpass_Text {
            get {
                return ResourceManager.GetString("lblmnuwtpass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काटा पार्च.
        /// </summary>
        internal static string lblmnuwweightslip_Text {
            get {
                return ResourceManager.GetString("lblmnuwweightslip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मोबाइल नंबर.
        /// </summary>
        internal static string lblMobileNo_Text {
            get {
                return ResourceManager.GetString("lblMobileNo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to खनिज का वजन.
        /// </summary>
        internal static string lblnetweight_Text {
            get {
                return ResourceManager.GetString("lblnetweight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ऑर्डर का विवरण.
        /// </summary>
        internal static string lblorderdetails_Text {
            get {
                return ResourceManager.GetString("lblorderdetails.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ऑर्डर लिस्ट.
        /// </summary>
        internal static string lblOrderList_Text {
            get {
                return ResourceManager.GetString("lblOrderList.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to समानता.
        /// </summary>
        internal static string lblparity_Text {
            get {
                return ResourceManager.GetString("lblparity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पासवर्ड.
        /// </summary>
        internal static string lblpassword_Text {
            get {
                return ResourceManager.GetString("lblpassword.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पोर्ट का नाम.
        /// </summary>
        internal static string lblpoartname_Text {
            get {
                return ResourceManager.GetString("lblpoartname.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रवाना.
        /// </summary>
        internal static string lblRawana_Text {
            get {
                return ResourceManager.GetString("lblRawana.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रीडर कोड.
        /// </summary>
        internal static string lblreadercode_Text {
            get {
                return ResourceManager.GetString("lblreadercode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टिप्पणी.
        /// </summary>
        internal static string lblremark_Text {
            get {
                return ResourceManager.GetString("lblremark.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रॉयल्टी अनुसूची दर.
        /// </summary>
        internal static string lblroyaltyschd_Text {
            get {
                return ResourceManager.GetString("lblroyaltyschd.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रॉयल्टी अनुसूची.
        /// </summary>
        internal static string lblroyaltyschedule_Text {
            get {
                return ResourceManager.GetString("lblroyaltyschedule.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to खोज.
        /// </summary>
        internal static string lblsearch_Text {
            get {
                return ResourceManager.GetString("lblsearch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रिपोर्ट.
        /// </summary>
        internal static string lblsreport_Text {
            get {
                return ResourceManager.GetString("lblsreport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थापना.
        /// </summary>
        internal static string lblssetting_Text {
            get {
                return ResourceManager.GetString("lblssetting.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सिस्टम टाइप.
        /// </summary>
        internal static string lblsssytemtype_Text {
            get {
                return ResourceManager.GetString("lblsssytemtype.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पता.
        /// </summary>
        internal static string lblstaddress_Text {
            get {
                return ResourceManager.GetString("lblstaddress.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कैमरा विवरण.
        /// </summary>
        internal static string lblstcameradtl_Text {
            get {
                return ResourceManager.GetString("lblstcameradtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to संस्थान के विवरण.
        /// </summary>
        internal static string lblstcdetail_Text {
            get {
                return ResourceManager.GetString("lblstcdetail.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सामने का कैमरा.
        /// </summary>
        internal static string lblstfcamera_Text {
            get {
                return ResourceManager.GetString("lblstfcamera.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्टॉप बिट्स.
        /// </summary>
        internal static string lblstopbits_Text {
            get {
                return ResourceManager.GetString("lblstopbits.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सीरियल पोर्ट सेटिंग.
        /// </summary>
        internal static string lblstportsetting_Text {
            get {
                return ResourceManager.GetString("lblstportsetting.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिछला कैमरा.
        /// </summary>
        internal static string lblstrcamera_Text {
            get {
                return ResourceManager.GetString("lblstrcamera.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काटा पार्च.
        /// </summary>
        internal static string lblsweightslip_Text {
            get {
                return ResourceManager.GetString("lblsweightslip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सिस्टम मोडल.
        /// </summary>
        internal static string lblsystemmodel_Text {
            get {
                return ResourceManager.GetString("lblsystemmodel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सिस्टम प्रकार.
        /// </summary>
        internal static string lblsystemtype_Text {
            get {
                return ResourceManager.GetString("lblsystemtype.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ख़ाली गाड़ी का वजन.
        /// </summary>
        internal static string lbltareweight_Text {
            get {
                return ResourceManager.GetString("lbltareweight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ख़ाली गाड़ी का वजन.
        /// </summary>
        internal static string lbltarewght_Text {
            get {
                return ResourceManager.GetString("lbltarewght.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परिवहन विवरण.
        /// </summary>
        internal static string lbltdtl_Text {
            get {
                return ResourceManager.GetString("lbltdtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टिकट संख्या.
        /// </summary>
        internal static string lblticketno_Text {
            get {
                return ResourceManager.GetString("lblticketno.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to क्षमता.
        /// </summary>
        internal static string lbltonnes_Text {
            get {
                return ResourceManager.GetString("lbltonnes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ट्रैन्ज़िट पास.
        /// </summary>
        internal static string lblTranistPass_Text {
            get {
                return ResourceManager.GetString("lblTranistPass.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परिवहन साधन.
        /// </summary>
        internal static string lbltransport_Text {
            get {
                return ResourceManager.GetString("lbltransport.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एमएल नंबर.
        /// </summary>
        internal static string lblucmlno_Text {
            get {
                return ResourceManager.GetString("lblucmlno.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पता.
        /// </summary>
        internal static string lbluctaddress_Text {
            get {
                return ResourceManager.GetString("lbluctaddress.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लगभग रॉयल्टी.
        /// </summary>
        internal static string lbluctapporxdtl_Text {
            get {
                return ResourceManager.GetString("lbluctapporxdtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लगभग समय.
        /// </summary>
        internal static string lbluctapproxtime_Text {
            get {
                return ResourceManager.GetString("lbluctapproxtime.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अनुमानित व़जन.
        /// </summary>
        internal static string lbluctapproxweigjt_Text {
            get {
                return ResourceManager.GetString("lbluctapproxweigjt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to क्षमता.
        /// </summary>
        internal static string lbluctcapcity_Text {
            get {
                return ResourceManager.GetString("lbluctcapcity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पार्टी डिटैल्ज़.
        /// </summary>
        internal static string lbluctconsdtl_Text {
            get {
                return ResourceManager.GetString("lbluctconsdtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जीएसटी.
        /// </summary>
        internal static string lbluctconsgst_Text {
            get {
                return ResourceManager.GetString("lbluctconsgst.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नाम.
        /// </summary>
        internal static string lbluctconsinme_Text {
            get {
                return ResourceManager.GetString("lbluctconsinme.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चालक मोबाइल.
        /// </summary>
        internal static string lbluctdrivermble_Text {
            get {
                return ResourceManager.GetString("lbluctdrivermble.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चालक का नाम.
        /// </summary>
        internal static string lbluctdrivername_Text {
            get {
                return ResourceManager.GetString("lbluctdrivername.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अन्कन्फर्म्ड ट्रैन्ज़िट पास.
        /// </summary>
        internal static string lbluctdtl_Text {
            get {
                return ResourceManager.GetString("lbluctdtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कुल वजन.
        /// </summary>
        internal static string lbluctgrosswght_Text {
            get {
                return ResourceManager.GetString("lbluctgrosswght.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थान.
        /// </summary>
        internal static string lbluctlocation_Text {
            get {
                return ResourceManager.GetString("lbluctlocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मिनरल्स.
        /// </summary>
        internal static string lbluctmineral_Text {
            get {
                return ResourceManager.GetString("lbluctmineral.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मिनरल्स यूज़्ड फॉर.
        /// </summary>
        internal static string lbluctmineralusefor_Text {
            get {
                return ResourceManager.GetString("lbluctmineralusefor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to खनिज का वजन.
        /// </summary>
        internal static string lbluctnetwght_Text {
            get {
                return ResourceManager.GetString("lbluctnetwght.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ई रवाना तिथि.
        /// </summary>
        internal static string lbluctrawannadate_Text {
            get {
                return ResourceManager.GetString("lbluctrawannadate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ई रवाना नंबर.
        /// </summary>
        internal static string lbluctrawannano_Text {
            get {
                return ResourceManager.GetString("lbluctrawannano.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सामने का कैमरा.
        /// </summary>
        internal static string lbluctrcamera_Text {
            get {
                return ResourceManager.GetString("lbluctrcamera.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टिप्पणी.
        /// </summary>
        internal static string lbluctremark_Text {
            get {
                return ResourceManager.GetString("lbluctremark.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्टेटस.
        /// </summary>
        internal static string lbluctstatus_Text {
            get {
                return ResourceManager.GetString("lbluctstatus.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परिवहन साधन.
        /// </summary>
        internal static string lblucttranportmode_Text {
            get {
                return ResourceManager.GetString("lblucttranportmode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परिवहन साधन.
        /// </summary>
        internal static string lblucttranportmodev_Text {
            get {
                return ResourceManager.GetString("lblucttranportmodev.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परिवहन विवरण.
        /// </summary>
        internal static string lblucttransportdtl_Text {
            get {
                return ResourceManager.GetString("lblucttransportdtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सौदे का प्रकार.
        /// </summary>
        internal static string lblucttrasportmode_Text {
            get {
                return ResourceManager.GetString("lblucttrasportmode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वाहन का वजन.
        /// </summary>
        internal static string lbluctvehicelwgt_Text {
            get {
                return ResourceManager.GetString("lbluctvehicelwgt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गाडी नंबर.
        /// </summary>
        internal static string lbluctvehicleno_Text {
            get {
                return ResourceManager.GetString("lbluctvehicleno.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वजन विवरण.
        /// </summary>
        internal static string lbluctweightdtl_Text {
            get {
                return ResourceManager.GetString("lbluctweightdtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पता.
        /// </summary>
        internal static string lblunaddress_Text {
            get {
                return ResourceManager.GetString("lblunaddress.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लगभग रॉयल्टी.
        /// </summary>
        internal static string lblunapproxroyality_Text {
            get {
                return ResourceManager.GetString("lblunapproxroyality.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लगभग समय.
        /// </summary>
        internal static string lblunapproxtime_Text {
            get {
                return ResourceManager.GetString("lblunapproxtime.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to क्षमता.
        /// </summary>
        internal static string lbluncapcity_Text {
            get {
                return ResourceManager.GetString("lbluncapcity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिछला कैमरा.
        /// </summary>
        internal static string lblunccamera_Text {
            get {
                return ResourceManager.GetString("lblunccamera.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ई रवाना तिथि.
        /// </summary>
        internal static string lblunconfdate_Text {
            get {
                return ResourceManager.GetString("lblunconfdate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अन्कन्फर्म्ड रवाना.
        /// </summary>
        internal static string lblunconfdtl_Text {
            get {
                return ResourceManager.GetString("lblunconfdtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्टेटस.
        /// </summary>
        internal static string lblunconfstatus_Text {
            get {
                return ResourceManager.GetString("lblunconfstatus.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पार्टी डिटैल्ज़.
        /// </summary>
        internal static string lblunconsignedtl_Text {
            get {
                return ResourceManager.GetString("lblunconsignedtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जीएसटी.
        /// </summary>
        internal static string lblunconsigneegst_Text {
            get {
                return ResourceManager.GetString("lblunconsigneegst.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नाम.
        /// </summary>
        internal static string lblunconsigneename_Text {
            get {
                return ResourceManager.GetString("lblunconsigneename.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चालक का नाम.
        /// </summary>
        internal static string lblundrivename_Text {
            get {
                return ResourceManager.GetString("lblundrivename.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चालक मोबाइल.
        /// </summary>
        internal static string lblundrivermobile_Text {
            get {
                return ResourceManager.GetString("lblundrivermobile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सामने का कैमरा.
        /// </summary>
        internal static string lblunfcamera_Text {
            get {
                return ResourceManager.GetString("lblunfcamera.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कुल वजन.
        /// </summary>
        internal static string lblungrossweight_Text {
            get {
                return ResourceManager.GetString("lblungrossweight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थान.
        /// </summary>
        internal static string lblunlocation_Text {
            get {
                return ResourceManager.GetString("lblunlocation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मिनरल्स.
        /// </summary>
        internal static string lblunmineralname_Text {
            get {
                return ResourceManager.GetString("lblunmineralname.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मिनरल्स यूज़्ड फॉर.
        /// </summary>
        internal static string lblunmineralusefor_Text {
            get {
                return ResourceManager.GetString("lblunmineralusefor.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to खनिज का वजन.
        /// </summary>
        internal static string lblunnetweight_Text {
            get {
                return ResourceManager.GetString("lblunnetweight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रवाना संख्या.
        /// </summary>
        internal static string lblunrawannano_Text {
            get {
                return ResourceManager.GetString("lblunrawannano.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टिप्पणी.
        /// </summary>
        internal static string lblunremark_Text {
            get {
                return ResourceManager.GetString("lblunremark.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रॉयल्टी अनुसूची दर.
        /// </summary>
        internal static string lblunroyalityrate_Text {
            get {
                return ResourceManager.GetString("lblunroyalityrate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रॉयल्टी अनुसूची.
        /// </summary>
        internal static string lblunroyalitysch_Text {
            get {
                return ResourceManager.GetString("lblunroyalitysch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to खोज.
        /// </summary>
        internal static string lblunsearch_Text {
            get {
                return ResourceManager.GetString("lblunsearch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ख़ाली गाड़ी का वजन.
        /// </summary>
        internal static string lbluntareweight_Text {
            get {
                return ResourceManager.GetString("lbluntareweight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परिवहन विवरण.
        /// </summary>
        internal static string lbluntransportdtl_Text {
            get {
                return ResourceManager.GetString("lbluntransportdtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परिवहन साधन.
        /// </summary>
        internal static string lbluntransportmode_Text {
            get {
                return ResourceManager.GetString("lbluntransportmode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गाडी नंबर.
        /// </summary>
        internal static string lblunvehiclenumb_Text {
            get {
                return ResourceManager.GetString("lblunvehiclenumb.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वाहन का वजन.
        /// </summary>
        internal static string lblunvehicleweight_Text {
            get {
                return ResourceManager.GetString("lblunvehicleweight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वजन विवरण.
        /// </summary>
        internal static string lblunweightdtl_Text {
            get {
                return ResourceManager.GetString("lblunweightdtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to उपयोगकर्ता नाम.
        /// </summary>
        internal static string lblusername_Text {
            get {
                return ResourceManager.GetString("lblusername.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गाडी नंबर.
        /// </summary>
        internal static string lblvechicle_Text {
            get {
                return ResourceManager.GetString("lblvechicle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काटा पार्च.
        /// </summary>
        internal static string lblweight_Text {
            get {
                return ResourceManager.GetString("lblweight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्वागत हे.
        /// </summary>
        internal static string lblwelcome_Text {
            get {
                return ResourceManager.GetString("lblwelcome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पता.
        /// </summary>
        internal static string lblwgaddress_Text {
            get {
                return ResourceManager.GetString("lblwgaddress.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to फर्म का नाम.
        /// </summary>
        internal static string lblwgfirmname_Text {
            get {
                return ResourceManager.GetString("lblwgfirmname.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सामग्री.
        /// </summary>
        internal static string lblwgmaterial_Text {
            get {
                return ResourceManager.GetString("lblwgmaterial.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काटा पार्च.
        /// </summary>
        internal static string lblwgslip_Text {
            get {
                return ResourceManager.GetString("lblwgslip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वजन विवरण.
        /// </summary>
        internal static string lblwgweightdtl_Text {
            get {
                return ResourceManager.GetString("lblwgweightdtl.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रवाना.
        /// </summary>
        internal static string lblwrawanna_Text {
            get {
                return ResourceManager.GetString("lblwrawanna.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दिनांक.
        /// </summary>
        internal static string lblwsdate_Text {
            get {
                return ResourceManager.GetString("lblwsdate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चालक मोबाइल नंबर.
        /// </summary>
        internal static string lblwsdrivermobno_Text {
            get {
                return ResourceManager.GetString("lblwsdrivermobno.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चालक का नाम.
        /// </summary>
        internal static string lblwsdrivernme_Text {
            get {
                return ResourceManager.GetString("lblwsdrivernme.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सामने का कैमरा.
        /// </summary>
        internal static string lblwsfcamera_Text {
            get {
                return ResourceManager.GetString("lblwsfcamera.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सामने का कैमरा.
        /// </summary>
        internal static string lblwsfcameras_Text {
            get {
                return ResourceManager.GetString("lblwsfcameras.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कुल वजन.
        /// </summary>
        internal static string lblwsgrossweight_Text {
            get {
                return ResourceManager.GetString("lblwsgrossweight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to खनिज का वजन.
        /// </summary>
        internal static string lblwsnetweight_Text {
            get {
                return ResourceManager.GetString("lblwsnetweight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिछला कैमरा.
        /// </summary>
        internal static string lblwsrcamera_Text {
            get {
                return ResourceManager.GetString("lblwsrcamera.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिछला कैमरा.
        /// </summary>
        internal static string lblwsrcameras_Text {
            get {
                return ResourceManager.GetString("lblwsrcameras.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टिप्पणी.
        /// </summary>
        internal static string lblwsremarks_Text {
            get {
                return ResourceManager.GetString("lblwsremarks.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ख़ाली गाड़ी का वजन.
        /// </summary>
        internal static string lblwstareweight_Text {
            get {
                return ResourceManager.GetString("lblwstareweight.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to गाडी नंबर.
        /// </summary>
        internal static string lblwsvehino_Text {
            get {
                return ResourceManager.GetString("lblwsvehino.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिछला कैमरा.
        /// </summary>
        internal static string lbuctrcamera_Text {
            get {
                return ResourceManager.GetString("lbuctrcamera.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सहायता.
        /// </summary>
        internal static string llblmnurphelp_Text {
            get {
                return ResourceManager.GetString("llblmnurphelp.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to माइन्स मार्ट में साइन इन करें.
        /// </summary>
        internal static string llbtitlelg_Text {
            get {
                return ResourceManager.GetString("llbtitlelg.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सीधा आदेश.
        /// </summary>
        internal static string rtdirect_Text {
            get {
                return ResourceManager.GetString("rtdirect.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आदेश पर.
        /// </summary>
        internal static string rtorder_Text {
            get {
                return ResourceManager.GetString("rtorder.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चालान छापें.
        /// </summary>
        internal static string rtprintinvoice_Text {
            get {
                return ResourceManager.GetString("rtprintinvoice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रिंट वजन पर्ची.
        /// </summary>
        internal static string rtprintweightslip_Text {
            get {
                return ResourceManager.GetString("rtprintweightslip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to खोज.
        /// </summary>
        internal static string UCTbtnsearch_Text {
            get {
                return ResourceManager.GetString("UCTbtnsearch.Text", resourceCulture);
            }
        }
    }
}
